window.PLANET_FACTS = {
  mercury: [
    "Mercury is the smallest planet in our solar system.",
    "A year on Mercury lasts just 88 Earth days.",
    "Mercury orbits the Sun faster than any other planet.",
    "Mercury is the closest planet to the Sun.",
    "Mercury has almost no atmosphere to trap heat.",
    "Temperatures on Mercury swing from -173°C at night to 427°C in the day.",
    "Mercury is named after the Roman messenger god.",
    "The Sun appears more than three times larger from Mercury than from Earth.",
    "Mercury has no moons and no rings.",
    "A single Mercury day lasts about 59 Earth days.",
    "Mercury is only slightly larger than Earth's Moon.",
    "Mercury is covered in craters, much like the Moon.",
    "The largest crater on Mercury is the Caloris Basin.",
    "Caloris Basin spans about 1,550 kilometres across.",
    "Mercury has ice hidden in permanently shadowed polar craters.",
    "Water ice on Mercury survives despite the planet's extreme heat.",
    "Mercury has a huge iron core that makes up most of its volume.",
    "Mercury's core may still be partially molten.",
    "Mercury has a weak magnetic field, about 1% of Earth's.",
    "The Mariner 10 probe was the first to visit Mercury in 1974.",
    "Mariner 10 mapped less than half of Mercury's surface.",
    "NASA's MESSENGER spacecraft orbited Mercury from 2011 to 2015.",
    "MESSENGER crashed into Mercury's surface when it ran out of fuel.",
    "The ESA and JAXA BepiColombo mission is currently heading to Mercury.",
    "Mercury is one of the least explored planets.",
    "Mercury has the most eccentric orbit of any planet.",
    "Mercury's orbit is noticeably more elliptical than the others.",
    "Sunrises on Mercury happen roughly once every 176 Earth days.",
    "From Mercury, the Sun can appear to move backward in the sky.",
    "Mercury's surface is heavily cratered and ancient.",
    "There are smooth plains on Mercury called intercrater plains.",
    "Mercury has 'wrinkle ridges' caused by the planet shrinking.",
    "Mercury may have shrunk by up to 14 kilometres in diameter.",
    "The planet's surface has cliffs that are kilometres tall.",
    "Discovery Rupes is a cliff on Mercury over 500 kilometres long.",
    "Mercury has no seasons to speak of.",
    "Mercury's axial tilt is the smallest of any planet.",
    "The planet spins almost perfectly upright.",
    "Mercury's gravity is about 38% of Earth's.",
    "You would weigh far less standing on Mercury.",
    "Mercury's sky is black even in daytime.",
    "Mercury reflects sunlight poorly, making it dark grey.",
    "Mercury is visible from Earth low near the horizon.",
    "Ancient astronomers called Mercury an evening or morning star.",
    "Mercury can be seen with the naked eye at dusk or dawn.",
    "The planet takes 88 days to complete one orbit.",
    "Mercury races along at nearly 48 kilometres per second.",
    "Mercury's surface gravity would let you jump about three times higher.",
    "The planet's atmosphere is a thin exosphere.",
    "Mercury's exosphere contains oxygen, sodium and hydrogen.",
    "Sodium in Mercury's exosphere glows faintly like a tail.",
    "Mercury has a comet-like tail of sodium atoms.",
    "Radar images revealed ice at Mercury's poles.",
    "The polar ice on Mercury is covered by a thin dark layer.",
    "Mercury is denser than it looks due to its giant core.",
    "Only Venus is closer to the Sun in terms of surface heat at day.",
    "Mercury has no global magnetic shield to block solar wind.",
    "The solar wind blasts Mercury's surface directly.",
    "Mercury's regolith is pulverized rock from endless impacts.",
    "The planet's craters can keep the cold for billions of years.",
    "Mercury's biggest mystery is why its core is so large.",
    "Scientists think Mercury may once have been much bigger.",
    "A giant impact may have stripped away Mercury's outer layers.",
    "Mercury may be the leftover core of a lost larger planet.",
    "The planet completes three rotations for every two orbits.",
    "This 3:2 spin-orbit resonance is unique among planets.",
    "One Mercury solar day equals two Mercury years.",
    "Mercury's surface shows volcanic plains from ancient lava.",
    "Hollows on Mercury are shallow pits found in crater floors.",
    "Hollows may form as volatile materials escape to space.",
    "Mercury's hollows are unique to the planet.",
    "The planet's surface is about 4 billion years old.",
    "Mercury's oldest terrains are among the oldest in the solar system.",
    "Mercury has radial graben systems called 'faults'.",
    "The planet is named in many languages after the same god.",
    "Mercury is the second-densest planet after Earth.",
    "Mercury's density hints at a mostly iron interior.",
    "The planet has no plate tectonics.",
    "Mercury's single plate is called the lithosphere.",
    "The planet contracts as its core slowly cools.",
    "Mercury's quakes may still happen as it shrinks.",
    "No spacecraft has landed on Mercury yet.",
    "Landing on Mercury is considered extremely difficult.",
    "Mercury's heat would melt many electronics within hours.",
    "The planet's day-night temperature difference is the largest.",
    "Mercury's proximity to the Sun makes it hard to reach.",
    "Probes must slow down against the Sun's gravity to enter orbit.",
    "Mercury appears only briefly in Earth's sky.",
    "The planet never strays far from the Sun as seen from Earth.",
    "Mercury is often lost in the Sun's glare.",
    "Copernicus never actually observed Mercury directly.",
    "Mercury's radius is about 2,440 kilometres.",
    "The planet is about 58 million kilometres from the Sun.",
    "Light takes about 3 minutes to reach Mercury from the Sun.",
    "Mercury's craters are named after artists and writers.",
    "The crater Tolstoy honours the famous Russian author.",
    "Beethoven, Shakespeare and Dickens all have craters on Mercury.",
    "The planet's features are named for deceased artists.",
    "Mercury is so small it could fit inside Earth about 18 times.",
    "Despite its size, Mercury has a surface gravity like Mars.",
    "Mercury will eventually be engulfed by the expanding Sun.",
    "In about 5 billion years, the Sun may swallow Mercury.",
    "Mercury is one of only four terrestrial planets."
  ],
  venus: [
    "Venus is the hottest planet in the solar system.",
    "Surface temperatures on Venus reach about 465°C.",
    "Venus is hotter than Mercury despite being farther from the Sun.",
    "Venus is wrapped in thick clouds of sulfuric acid.",
    "The planet has a crushing atmosphere of carbon dioxide.",
    "Air pressure on Venus is about 90 times that of Earth.",
    "Standing on Venus would crush you instantly.",
    "Venus rotates backwards compared to most planets.",
    "On Venus the Sun rises in the west and sets in the east.",
    "A single day on Venus lasts 243 Earth days.",
    "A Venus year is only 225 Earth days.",
    "So a Venus day is longer than its year.",
    "Venus is named after the Roman goddess of love and beauty.",
    "Venus is the brightest natural object in Earth's night sky after the Moon.",
    "Ancient people called Venus the Morning Star and Evening Star.",
    "Venus is sometimes called Earth's twin.",
    "Venus and Earth are nearly the same size.",
    "Venus has the most circular orbit of any planet.",
    "The planet has no moons and no rings.",
    "Venus spins almost upside down with a tilt of 177°.",
    "The surface of Venus is hidden by dense clouds.",
    "Soviet Venera probes were the first to land on Venus.",
    "Venera 7 made the first soft landing on another planet in 1970.",
    "Venera 13 sent back the first colour photos from Venus' surface.",
    "The Venera landers survived only minutes in the heat.",
    "Venus' surface is young, geologically speaking.",
    "The planet is covered in vast volcanic plains.",
    "Venus has more volcanoes than any other planet.",
    "There are over 1,600 major volcanoes on Venus.",
    "Maxwell Montes is the highest mountain on Venus.",
    "Maxwell Montes rises about 11 kilometres high.",
    "Venus has two large highland continents.",
    "Ishtar Terra and Aphrodite Terra are the big highlands.",
    "Venus is dotted with pancake-shaped volcanoes.",
    "These pancake domes form from thick sticky lava.",
    "Coronae on Venus are huge crown-shaped geological features.",
    "Coronae may mark spots where mantle plumes rose.",
    "Venus' surface is mostly basalt rock.",
    "The planet's crust may be less than 1 billion years old.",
    "Venus has no plate tectonics like Earth.",
    "Instead of plates, Venus has a single intact crust.",
    "The planet's atmosphere spins much faster than the surface.",
    "Winds on Venus can reach 300 kilometres per hour.",
    "These super-rotating winds circle the planet every 4 days.",
    "Venus has the longest day of any planet.",
    "The planet's slow spin may explain its weird weather.",
    "Venus has no seasons because of its minimal tilt.",
    "Lightning has been detected in Venus' clouds.",
    "The clouds of Venus may contain living microbes.",
    "Phosphine gas was once tentatively detected in the clouds.",
    "The phosphine finding remains hotly debated.",
    "Venus' clouds are made of sulfuric acid droplets.",
    "The planet is dry with almost no water vapour.",
    "Venus likely lost its water long ago.",
    "Solar wind stripped away Venus' early water.",
    "Runaway greenhouse effect made Venus hellish.",
    "Venus is the classic example of a runaway greenhouse planet.",
    "The planet radiates more heat than it receives from the Sun.",
    "Venus reflects about 75% of incoming sunlight.",
    "Its high reflectivity makes Venus shine so brightly.",
    "The clouds of Venus are yellowish-white in colour.",
    "From the surface, Venus' sky would appear orange.",
    "The ground on Venus is lit like an overcast day on Earth.",
    "Despite the heat, some places are cooler at higher altitude.",
    "The upper cloud tops of Venus are pleasant by Earth standards.",
    "Venus' surface is scorching because of the dense CO2.",
    "The planet has acid rain that never reaches the ground.",
    "Sulfuric acid rain evaporates before hitting the surface.",
    "Venus has 'snow' made of metal compounds on its peaks.",
    "Mountaintops on Venus are coated in shiny minerals.",
    "These metallic frosts may be lead sulfide.",
    "Venus is visible even during the day if you know where to look.",
    "Galileo first observed the phases of Venus in 1610.",
    "The phases of Venus proved it orbited the Sun.",
    "Venus transits across the Sun happen in pairs 8 years apart.",
    "The last Venus transit was in 2012; the next is in 2117.",
    "Edmond Halley suggested using Venus transits to measure distance.",
    "Captain Cook sailed to observe a Venus transit in 1769.",
    "Venus is the only planet named after a female deity.",
    "Most planets are named after male gods.",
    "The Venus symbol represents a hand mirror.",
    "The planet is associated with the female gender symbol.",
    "NASA's Magellan spacecraft mapped Venus with radar.",
    "Magellan revealed the planet's hidden surface in the 1990s.",
    "The ESA's Venus Express orbited the planet from 2006 to 2014.",
    "Japan's Akatsuki probe is currently studying Venus.",
    "NASA plans new Venus missions called DAVINCI and VERITAS.",
    "DAVINCI will drop a probe through Venus' atmosphere.",
    "VERITAS will map Venus' surface in high detail.",
    "Venus is about 108 million kilometres from the Sun.",
    "Venus has a diameter of about 12,104 kilometres.",
    "Venus is slightly smaller than Earth.",
    "You would weigh about 91% of your Earth weight on Venus.",
    "Venus' gravity is nearly the same as Earth's.",
    "No probe has survived long on Venus' surface.",
    "The longest any lander survived was about two hours.",
    "Venus' atmosphere extends far above the surface.",
    "The planet's gravity is too weak to hold onto water.",
    "Venus' core may be similar in size to Earth's.",
    "Venus has no global magnetic field.",
    "The lack of a field leaves Venus exposed to the solar wind.",
    "Venus is the third-brightest object in the entire sky.",
    "Only the Sun and Moon outshine Venus.",
    "Venus can cast shadows on Earth on the darkest nights.",
    "Some ancient cultures thought Venus was two separate stars."
  ],
  earth: [
    "Earth is the only known planet to harbour life.",
    "Earth is the fifth-largest planet in the solar system.",
    "About 71% of Earth's surface is covered by water.",
    "Earth is the only planet with liquid water on its surface.",
    "Earth is nicknamed the Blue Planet.",
    "The name 'Earth' comes from old English and Germanic words.",
    "Earth is the only planet not named after a god.",
    "Earth orbits the Sun at about 107,000 kilometres per hour.",
    "One Earth year takes about 365.25 days.",
    "We add a leap day every four years to fix that fraction.",
    "Earth's rotation is slowing down over time.",
    "Earthquakes can slightly change the length of a day.",
    "Earth's axis is tilted by about 23.5 degrees.",
    "That tilt gives us our four seasons.",
    "Earth is the densest planet in the solar system.",
    "Earth's core is as hot as the Sun's surface.",
    "The inner core is a solid ball of iron and nickel.",
    "The outer core is liquid metal that generates our magnetic field.",
    "Earth's magnetic field protects us from solar radiation.",
    "The magnetic north pole is constantly moving.",
    "Earth's atmosphere is about 78% nitrogen.",
    "Oxygen makes up about 21% of the atmosphere.",
    "The remaining 1% is argon, CO2 and other gases.",
    "Earth's ozone layer shields life from UV rays.",
    "The ozone hole over Antarctica is slowly healing.",
    "Earth is home to an estimated 8.7 million species.",
    "Most species on Earth have never even been named.",
    "Over 99% of all species that ever lived are now extinct.",
    "Earth's oceans contain about 97% of its water.",
    "Only about 3% of Earth's water is fresh.",
    "Most fresh water is locked in ice caps and glaciers.",
    "Mount Everest is the highest point above sea level.",
    "Mount Everest rises about 8,849 metres.",
    "The Mariana Trench is the deepest ocean point.",
    "The Mariana Trench plunges about 11,000 metres down.",
    "Earth is a rocky planet with a thin crust.",
    "The crust is only about 5 to 70 kilometres thick.",
    "Tectonic plates carry continents around the globe.",
    "Continents drift about as fast as fingernails grow.",
    "Pangaea was Earth's single supercontinent 200 million years ago.",
    "Earth has one natural satellite: the Moon.",
    "The Moon stabilizes Earth's axial tilt.",
    "The Moon causes ocean tides through gravity.",
    "Earth is 4.54 billion years old.",
    "Life appeared on Earth about 3.7 billion years ago.",
    "Dinosaurs ruled Earth for about 165 million years.",
    "Humans have existed for only a tiny fraction of Earth's history.",
    "Earth's oldest known rocks are about 4 billion years old.",
    "The planet's surface is constantly being recycled.",
    "Plate subduction drags old crust back into the mantle.",
    "New crust forms at mid-ocean ridges.",
    "Earth is the only planet with active plate tectonics.",
    "Earthquakes release energy that travels as seismic waves.",
    "Volcanoes erupt at plate boundaries and hot spots.",
    "Earth has about 1,500 potentially active volcanoes.",
    "Most volcanoes are hidden beneath the oceans.",
    "Earth's atmosphere extends about 10,000 kilometres.",
    "The Karman line at 100 km marks the edge of space.",
    "Earth receives energy from the Sun through fusion.",
    "The planet's climate has swung between ice ages and warm periods.",
    "Earth's average temperature is about 15°C.",
    "The coldest place on Earth is Antarctica.",
    "Temperatures in Antarctica can drop below -89°C.",
    "The hottest recorded temperature was about 56.7°C.",
    "Earth spins at roughly 1,670 kilometres per hour at the equator.",
    "You are moving through space right now at huge speeds.",
    "Earth travels about 940 million kilometres each year.",
    "Earth is not a perfect sphere but slightly squashed.",
    "Earth bulges at the equator due to its spin.",
    "The planet's gravity is not perfectly uniform.",
    "Earth's ocean surface has its own hills and valleys.",
    "About 40,000 tonnes of space dust hit Earth yearly.",
    "Meteors are common; asteroid impacts are rare.",
    "The Chicxulub impact killed the dinosaurs 66 million years ago.",
    "Earth's orbit is almost circular.",
    "Earth is between 147 and 152 million kilometres from the Sun.",
    "Light from the Sun takes about 8 minutes to reach Earth.",
    "Earth's rotation gives us day and night.",
    "The planet completes a rotation every 24 hours.",
    "The International Space Station orbits Earth every 90 minutes.",
    "Astronauts see about 16 sunrises a day on the ISS.",
    "Earth is the only place where water exists in all three states.",
    "Ice, liquid water and steam all occur naturally on Earth.",
    "Earth's forests are called the lungs of the planet.",
    "The Amazon produces about 20% of Earth's oxygen.",
    "Earth's polar ice caps are melting as the climate warms.",
    "The planet has experienced five mass extinctions.",
    "We may be living through a sixth mass extinction today.",
    "Earth's biosphere extends from the deep sea to the upper clouds.",
    "Life has been found miles beneath the sea floor.",
    "Some microbes on Earth can survive in nuclear reactors.",
    "Earth's highest clouds form around 80 kilometres up.",
    "The planet's lightning strikes about 8 million times a day.",
    "Thunder is the sound of rapidly expanding air.",
    "Earth has deserts, rainforests, tundra and grasslands.",
    "The Sahara is the largest hot desert on Earth.",
    "Antarctica is technically a cold desert.",
    "Earth's magnetic reversals have happened many times.",
    "The last geomagnetic reversal was about 780,000 years ago.",
    "Earth is unique in having a large moon relative to its size.",
    "The Moon formed from a giant impact early in Earth's history.",
    "Earth is the benchmark for habitability in the universe."
  ],
  mars: [
    "Mars is called the Red Planet because of iron oxide dust.",
    "Mars is the fourth planet from the Sun.",
    "A day on Mars lasts 24.6 hours, very close to Earth's.",
    "A year on Mars lasts about 687 Earth days.",
    "Mars is about half the size of Earth.",
    "Mars has two small moons called Phobos and Deimos.",
    "Phobos and Deimos are probably captured asteroids.",
    "Mars is named after the Roman god of war.",
    "The red colour of Mars comes from rusting iron.",
    "Mars has the largest volcano in the solar system.",
    "Olympus Mons is about 22 kilometres tall.",
    "Olympus Mons is three times taller than Mount Everest.",
    "Mars hosts the largest canyon system too.",
    "Valles Marineris stretches over 4,000 kilometres.",
    "Valles Marineris is up to 7 kilometres deep.",
    "Mars has polar ice caps made of water ice and CO2.",
    "The caps grow and shrink with the Martian seasons.",
    "Mars once had liquid water on its surface.",
    "Ancient riverbeds and lakebeds are visible on Mars.",
    "Mars may have had an ocean in its northern hemisphere.",
    "The planet lost most of its atmosphere long ago.",
    "Solar wind stripped away Mars' protective atmosphere.",
    "Mars once had a strong magnetic field; it faded away.",
    "Today Mars' atmosphere is 95% carbon dioxide.",
    "Mars' air pressure is about 1% of Earth's.",
    "Dust storms on Mars can engulf the entire planet.",
    "Some Martian dust storms last for months.",
    "Mars has seasons like Earth because of a similar tilt.",
    "Mars' tilt is about 25 degrees.",
    "Average temperature on Mars is about -63°C.",
    "Mars can dip to -140°C at the poles in winter.",
    "Mars' equator can reach a comfortable 20°C on summer days.",
    "Mars has dust devils that clean rover solar panels.",
    "The Opportunity rover survived thanks to wind cleaning.",
    "NASA's first Mars landers were Viking 1 and 2 in 1976.",
    "Sojourner was the first Mars rover, landing in 1997.",
    "Spirit and Opportunity landed in 2004.",
    "Opportunity lasted over 14 years on Mars.",
    "Curiosity rover landed in 2012 in Gale Crater.",
    "Curiosity found evidence of ancient habitable lakes.",
    "Perseverance rover landed in 2021 in Jezero Crater.",
    "Perseverance is caching samples for return to Earth.",
    "The Ingenuity helicopter made the first flight on another world.",
    "Ingenuity flew over 70 times on Mars.",
    "The first Mars rover photo was black and white.",
    "Mars is visible to the naked eye from Earth.",
    "Mars looks reddish-orange in the night sky.",
    "Ancient cultures saw Mars as a wandering red star.",
    "Mars has giant canyons, volcanoes and dunes.",
    "The planet's soil is rich in iron oxide.",
    "Mars has the tallest known mountain and deepest canyon.",
    "Phobos orbits Mars so closely it rises and sets twice a day.",
    "Phobos is slowly spiraling toward Mars.",
    "In millions of years Phobos will crash or become a ring.",
    "Deimos is tiny and barely holds its shape.",
    "Mars has no global magnetic field today.",
    "The planet's atmosphere is too thin for liquid water now.",
    "Salty brines may briefly flow on Martian slopes.",
    'Seasonal streaks called recurring slope lineae were once debated.',
    "Mars has massive canyons cut by ancient floods.",
    "A giant flood once carved outflow channels on Mars.",
    "Mars' northern plains are unusually flat.",
    "The planet's crust is thicker in the southern highlands.",
    "Mars has a south-north dichotomy in elevation.",
    "Water ice lies just beneath parts of the Martian surface.",
    "Mars' polar layered deposits record climate history.",
    "The planet wobbles much more than Earth does.",
    "Mars' moons are named for the horses of the war god.",
    "Phobos means 'fear' and Deimos means 'panic'.",
    "Mars is the most explored planet beyond Earth.",
    "Dozens of missions have been sent to Mars.",
    "About half of all Mars missions have failed.",
    "The Mars 'Curse' earned a reputation among mission planners.",
    "China's Tianwen-1 landed its rover Zhurong in 2021.",
    "The UAE's Hope probe studies Mars' atmosphere.",
    "The ESA's ExoMars rover is planned to drill for life.",
    "Humans could land on Mars within the coming decades.",
    "Mars gravity is 38% of Earth's.",
    "You would weigh about 38% of your Earth weight on Mars.",
    "Mars has no ozone layer to block radiation.",
    "Radiation levels on Mars are far higher than on Earth.",
    "Mars' sky is reddish during dust storms.",
    "At sunset on Mars, the sky appears blue.",
    "Mars' dust is fine enough to stick to everything.",
    "Martian dust can carry static electricity.",
    "The planet gets huge planet-wide dust storms.",
    "Mars has features called 'spiders' near the poles.",
    "Those spider patterns form as CO2 ice sublimates in spring.",
    "Mars' surface has gullies that may be carved by CO2.",
    "The planet may still have volcanic activity.",
    "Seismic events called marsquakes have been detected.",
    "NASA's InSight lander measured marsquakes until 2022.",
    "Mars' core is probably liquid and larger than thought.",
    "The planet's mantle appears to hold water.",
    "Mars could support crops in controlled greenhouse domes.",
    "The planet's thin air cannot protect from meteoroids.",
    "Mars is hit by frequent small meteor impacts.",
    "Fresh impact craters are spotted regularly on Mars.",
    "Mars is a prime target in the search for past life."
  ],
  jupiter: [
    "Jupiter is the largest planet in the solar system.",
    "Jupiter is more than twice as massive as all other planets combined.",
    "Jupiter is called a gas giant for good reason.",
    "More than 1,300 Earths could fit inside Jupiter.",
    "Jupiter is the fifth planet from the Sun.",
    "A year on Jupiter lasts about 12 Earth years.",
    "A day on Jupiter lasts under 10 hours.",
    "Jupiter spins faster than any other planet.",
    "Its fast spin flattens Jupiter into an oblate spheroid.",
    "Jupiter is named after the king of the Roman gods.",
    "Jupiter has the shortest day of all planets.",
    "The Great Red Spot is Jupiter's most famous feature.",
    "The Great Red Spot is a giant storm bigger than Earth.",
    "The storm has raged for hundreds of years.",
    "The Great Red Spot is slowly shrinking.",
    "Jupiter has bands of clouds in cream, brown and orange.",
    "Those bands are caused by fast-moving jet streams.",
    "Jupiter's clouds are made of ammonia crystals.",
    "The planet's stripes are called zones and belts.",
    "Jupiter has a faint ring system made of dust.",
    "Jupiter's rings were discovered by the Voyager probes.",
    "The planet has at least 95 known moons.",
    "Io is Jupiter's most volcanically active moon.",
    "Io has more than 400 active volcanoes.",
    "Europa hides a salty ocean beneath its icy crust.",
    "Europa's ocean may contain twice the water of Earth's.",
    "Ganymede is the largest moon in the solar system.",
    "Ganymede is bigger than the planet Mercury.",
    "Callisto is the most heavily cratered world known.",
    "Galileo discovered the four largest moons in 1610.",
    "Those four moons are now called the Galilean moons.",
    "Jupiter's gravity is about 2.4 times Earth's.",
    "You would weigh about 2.4 times more on Jupiter.",
    "Jupiter has no solid surface to stand on.",
    "The planet's core may be hot and compressed.",
    "Hydrogen acts like a metal deep inside Jupiter.",
    "Metallic hydrogen may generate Jupiter's magnetic field.",
    "Jupiter's magnetic field is the strongest of any planet.",
    "Its magnetic field is about 20,000 times Earth's.",
    "Jupiter's auroras are the most powerful in the solar system.",
    "The planet's radiation belts are extremely hazardous.",
    "Jupiter's magnetosphere is the largest structure in the solar system.",
    "The planet emits more heat than it receives from the Sun.",
    "Jupiter's interior is still contracting and heating up.",
    "Jupiter is about 778 million kilometres from the Sun.",
    "Light from the Sun takes 43 minutes to reach Jupiter.",
    "Jupiter's Great Red Spot has winds over 400 kilometres per hour.",
    "Jupiter is visible to the naked eye from Earth.",
    "Ancient astronomers knew Jupiter as a wandering star.",
    "The planet can be one of the brightest objects in the night sky.",
    "Jupiter has hosted many spacecraft over the years.",
    "Pioneer 10 flew past Jupiter in 1973.",
    "Voyager 1 and 2 studied Jupiter in 1979.",
    "Voyager revealed Jupiter's faint rings and active volcanoes on Io.",
    "Galileo orbited Jupiter from 1995 to 2003.",
    "Galileo dropped a probe into Jupiter's atmosphere.",
    "That probe survived 200 kilometres before being crushed.",
    "Cassini flew by Jupiter in 2000 on its way to Saturn.",
    "New Horizons passed Jupiter in 2007 on its way to Pluto.",
    "NASA's Juno has orbited Jupiter since 2016.",
    "Juno is studying Jupiter's interior and magnetic field.",
    "The ESA's JUICE mission is heading to Jupiter's icy moons.",
    "JUICE will focus on Ganymede, Callisto and Europa.",
    "Jupiter may have helped shape the early solar system.",
    "The planet may have migrated inward then outward long ago.",
    "Jupiter's gravity deflects many comets away from Earth.",
    "It also flings some objects toward the inner solar system.",
    "The Shoemaker-Levy 9 comet crashed into Jupiter in 1994.",
    "The impact left scars bigger than Earth.",
    "Jupiter protects inner planets by acting as a cosmic shield.",
    "The planet's moon Europa is a prime target for life search.",
    "Europa Clipper mission will explore the icy moon.",
    "Jupiter's moon Io is the most volcanically active world.",
    "Io's volcanoes erupt sulfur at huge heights.",
    "Tidal flexing powers Io's volcanoes.",
    "Jupiter's moons show incredible diversity.",
    "The planet has clouds at very different heights.",
    "Jupiter's upper atmosphere contains lightning.",
    "Lightning bolts on Jupiter can be far larger than Earth's.",
    "Jupiter's storm systems can swallow entire planets.",
    "The planet's oval storms come in white, brown and red.",
    "Jupiter has a 'bow shock' where solar wind meets its field.",
    "The planet creates the largest auroras seen anywhere.",
    "Jupiter's faint rings are mainly dark dust.",
    "The rings likely come from impacts on its moons.",
    "Jupiter is composed mostly of hydrogen and helium.",
    "Its composition mirrors the Sun's original material.",
    "Jupiter is often called a failed star.",
    "It would need 80 times more mass to ignite fusion.",
    "Jupiter radiates about 1.6 times the energy it receives.",
    "The planet's radio emissions were detected on Earth.",
    "Jupiter is a strong source of radio noise.",
    "Amateur astronomers can observe Jupiter's moons with binoculars.",
    "Jupiter can be seen with the naked eye most of the year.",
    "The planet was observed by ancient Babylonians and Chinese.",
    "Galileo's telescope observations changed astronomy forever.",
    "Jupiter's moons were the first objects found orbiting another world.",
    "The discovery proved not everything orbits Earth.",
    "Jupiter has a possible Trojan asteroid population in its orbit.",
    "Trojans share Jupiter's orbit ahead and behind.",
    "Jupiter's immense gravity shapes the asteroid belt.",
    "The planet is the undisputed king of the solar system."
  ],
  saturn: [
    "Saturn is famous for its spectacular ring system.",
    "Saturn is the second-largest planet in the solar system.",
    "Saturn is the sixth planet from the Sun.",
    "Saturn is a gas giant like Jupiter.",
    "The planet is named after the Roman god of agriculture.",
    "Saturn is the least dense planet in the solar system.",
    "Saturn could float in water, if you found an ocean big enough.",
    "Saturn's density is lower than that of water.",
    "A day on Saturn lasts about 10.7 hours.",
    "A year on Saturn lasts about 29 Earth years.",
    "Saturn's rings are made of ice and rock.",
    "The rings stretch over 280,000 kilometres wide.",
    "The rings are incredibly thin, often only tens of metres thick.",
    "Saturn's rings are divided into many named bands.",
    "The gaps in the rings are caused by moons.",
    "The Cassini Division is the biggest gap in the rings.",
    "Saturn's rings are constantly changing.",
    "Ring particles range from dust grains to house-sized boulders.",
    "Saturn's rings may be as young as 100 million years.",
    "The rings may eventually disappear entirely.",
    'Ring "spokes" are mysterious dark streaks that come and go.',
    "Saturn has at least 146 known moons.",
    "Titan is Saturn's largest moon.",
    "Titan is bigger than the planet Mercury.",
    "Titan has a thick orange atmosphere.",
    "Titan is the only moon with a dense atmosphere.",
    "Titan has rivers and lakes of liquid methane.",
    "Titan's surface pressure is about 1.5 times Earth's.",
    "Enceladus is Saturn's most dramatic moon.",
    "Enceladus shoots jets of water from its south pole.",
    "Those geysers come from a hidden subsurface ocean.",
    "Enceladus is a top target in the search for life.",
    "Saturn has a hexagonal storm at its north pole.",
    "The hexagon was discovered by the Voyager probes.",
    "The hexagon is about 30,000 kilometres across.",
    "A huge hurricane sits at Saturn's north pole.",
    "Saturn's winds can exceed 1,800 kilometres per hour.",
    "Saturn's winds are among the fastest in the solar system.",
    "Saturn is about 1.4 billion kilometres from the Sun.",
    "Light takes about 80 minutes to travel from Sun to Saturn.",
    "Saturn's gravity is slightly more than Earth's.",
    "You would weigh about 1.07 times more on Saturn.",
    "Saturn has no solid surface.",
    "Saturn's interior hides a dense core of rock and metal.",
    "Saturn radiates more heat than it receives from the Sun.",
    "The planet's warmth may come from helium rain.",
    "Helium rain inside Saturn may generate heat.",
    "Saturn's magnetic field is weaker than Jupiter's but strong.",
    "Saturn's auroras glow at its poles.",
    "Saturn's rings are incredibly bright in telescopes.",
    "Galileo first saw Saturn's rings in 1610.",
    "Galileo thought the rings were ears or handles.",
    "Christiaan Huygens correctly described the rings in 1655.",
    "Huygens also discovered Saturn's moon Titan.",
    "Giovanni Cassini found the gap named after him in 1675.",
    "Saturn can be seen with the naked eye from Earth.",
    "Saturn appears as a pale golden point in the night sky.",
    "Saturn is the most distant planet visible without a telescope.",
    "Pioneer 11 flew past Saturn in 1979.",
    "Voyager 1 passed Saturn in 1980.",
    "Voyager 2 passed Saturn in 1981.",
    "Voyager discovered Saturn's complex moon system.",
    "The Cassini spacecraft orbited Saturn from 2004 to 2017.",
    "Cassini studied Saturn for over 13 years.",
    "Cassini dropped the Huygens probe onto Titan in 2005.",
    "Huygens made the first landing on an outer planet moon.",
    "Cassini ended its mission by diving into Saturn in 2017.",
    "The Grand Finale dives sampled Saturn's atmosphere.",
    "Saturn's rings may be made from a shattered moon.",
    "A moon torn apart could have formed the rings.",
    "Saturn's rings are almost pure water ice.",
    "Fresh ice makes the rings look bright.",
    "Saturn's moon Mimas looks like the Death Star.",
    "Mimas has a giant crater called Herschel.",
    "Saturn's moon Iapetus has a two-toned surface.",
    "Iapetus is bright on one side and dark on the other.",
    "Saturn's moon Rhea may have its own faint rings.",
    "The planet has shepherd moons that shape its rings.",
    "Prometheus and Pandora are shepherd moons.",
    "Saturn's moon Pan keeps the Encke Gap clear.",
    "Saturn has tiny moonlets embedded in its rings.",
    "Titan's lakes are filled with liquid ethane and methane.",
    "Titan may have a water ocean beneath its crust.",
    "Titan is considered a candidate for exotic life.",
    "Saturn's hexagon may be linked to its jet stream.",
    "The hexagon rotates with Saturn's spin.",
    "Saturn's clouds are arranged in subtle pastel bands.",
    "The planet's colour is a pale yellow-gold.",
    "Saturn's poles look slightly flattened due to fast spin.",
    "The planet's ring plane is tilted about 27 degrees.",
    "Every 15 years the rings appear edge-on to Earth.",
    "When edge-on, the rings seem to vanish.",
    "Saturn has equinox events when sunlight hits ring edges.",
    "Saturn's rings cast shadows on the planet.",
    "Storms on Saturn can be visible from Earth.",
    "A huge storm in 2010 circled the entire planet.",
    "That storm lasted for months.",
    "Saturn is a favourite target for amateur astrophotographers.",
    "Saturn's beauty makes it the showpiece of the night sky."
  ],
  uranus: [
    "Uranus is the seventh planet from the Sun.",
    "Uranus is an ice giant, not a gas giant.",
    "Uranus was the first planet found with a telescope.",
    "William Herschel discovered Uranus in 1781.",
    "Uranus is named after the Greek god of the sky.",
    "Uranus spins on its side with a tilt of 98 degrees.",
    "Uranus rolls around the Sun like a barrel.",
    "The planet's unusual tilt likely came from a giant impact.",
    "A huge collision may have knocked Uranus sideways.",
    "Uranus' poles point almost toward the Sun.",
    "Each pole gets 42 years of sunlight and 42 of darkness.",
    "Uranus has the most extreme seasons in the solar system.",
    "Uranus is a pale blue-green colour.",
    "Methane in its atmosphere gives Uranus its colour.",
    "Methane absorbs red light and reflects blue.",
    "Uranus has the coldest atmosphere of any planet.",
    "Temperatures can drop to about -224°C on Uranus.",
    "Uranus is colder than Neptune despite being closer to the Sun.",
    "The planet radiates very little internal heat.",
    "Uranus' faint heat output remains a mystery.",
    "Uranus has a faint ring system.",
    "Uranus' rings were discovered in 1977.",
    "The rings were found when they blocked a star's light.",
    "Uranus has 13 known rings.",
    "Uranus' rings are dark and narrow.",
    "The planet has at least 28 known moons.",
    "Uranus' moons are named after Shakespeare characters.",
    "Titania and Oberon are from 'A Midsummer Night's Dream'.",
    "Miranda is named after a character in 'The Tempest'.",
    "Miranda has one of the strangest surfaces known.",
    "Miranda's landscape looks like a patchwork of regions.",
    "Ariel and Umbriel also come from Shakespeare.",
    "Uranus' moons are mostly ice and rock.",
    "The moons may have subsurface oceans.",
    "Uranus is about 2.9 billion kilometres from the Sun.",
    "Light from the Sun takes about 2.7 hours to reach Uranus.",
    "A year on Uranus lasts about 84 Earth years.",
    "A day on Uranus lasts about 17 hours.",
    "Uranus' rotation is retrograde, spinning backward.",
    "Uranus is about four times wider than Earth.",
    "More than 60 Earths could fit inside Uranus.",
    "Uranus has no solid surface.",
    "The planet's core is rocky, surrounded by icy mantle.",
    "Uranus' mantle is made of water, methane and ammonia ices.",
    "Uranus is sometimes called an ice giant because of this.",
    "Neptune and Uranus are both ice giants.",
    "Uranus was briefly called 'Georgium Sidus'.",
    "Herschel named it after King George III.",
    "The name Uranus took decades to catch on.",
    "Uranus is visible to the naked eye under dark skies.",
    "Ancient observers may have seen Uranus without knowing it.",
    "Uranus was mistaken for a star for many years.",
    "The planet is barely visible to the naked eye.",
    "Only one spacecraft has visited Uranus.",
    "Voyager 2 flew past Uranus in 1986.",
    "Voyager 2 is the only probe to reach Uranus.",
    "Voyager mapped Uranus' moons and rings.",
    "Voyager discovered 10 new moons of Uranus.",
    "No mission has orbited Uranus yet.",
    "Scientists have proposed a Uranus orbiter mission.",
    "A future mission could launch in the 2030s.",
    "Uranus' magnetic field is weirdly tilted.",
    "Its magnetic field is offset from its centre.",
    "Uranus' magnetic poles are far from its geographic poles.",
    "The magnetosphere is lopsided and strange.",
    "Uranus' auroras are faint and mysterious.",
    "Uranus has bands of clouds, but they are subtle.",
    "The planet looks smooth compared to Jupiter.",
    "Uranus' clouds are mostly methane.",
    "Storms on Uranus have been spotted by telescopes.",
    "The planet's upper atmosphere is full of haze.",
    "Uranus' rings are made of dark particles.",
    "The rings may be younger than the planet.",
    "Uranus' moon Miranda has giant canyons.",
    "Verona Rupes on Miranda is a huge cliff.",
    "Verona Rupes may be 20 kilometres high.",
    "Uranus' moons are composed of ice and rock.",
    "The moons may have formed from a disc around Uranus.",
    "Uranus' axial tilt gives it bizarre seasons.",
    "During summer, the Sun shines almost straight down on a pole.",
    "Uranus' equator is nearly at right angles to its orbit.",
    "The planet's odd tilt affects its entire system.",
    "Uranus' moon system is tilted the same way.",
    "The Uranian system is tipped on its side.",
    "Uranus' rings are nearly vertical in some views.",
    "Uranus has a 'dark pole' in some observations.",
    "Seasonal changes on Uranus last decades.",
    "Uranus' atmosphere is mostly hydrogen and helium.",
    "Methane is only a small fraction of the air.",
    "Uranus' internal heat output is unusually low.",
    "Neptune radiates much more heat than Uranus.",
    "The reason for the difference is unknown.",
    "Uranus was the first planet discovered in modern times.",
    "Uranus expanded our understanding of the solar system.",
    "The planet completes an orbit every 84 years.",
    "Uranus last visited its equinox in 2007.",
    "The equinox gave a good view of its rings.",
    "Uranus remains one of the least explored planets."
  ],
  neptune: [
    "Neptune is the most distant planet from the Sun.",
    "Neptune is the eighth planet in the solar system.",
    "Neptune is an ice giant like Uranus.",
    "Neptune is named after the Roman god of the sea.",
    "Neptune was discovered by mathematics before telescopes.",
    "Urbain Le Verrier predicted Neptune's position in 1846.",
    "Johann Galle found Neptune the same year.",
    "Neptune is a deep, vivid blue colour.",
    "Methane gives Neptune its blue hue.",
    "Neptune has the strongest winds of any planet.",
    "Winds on Neptune can reach 2,100 kilometres per hour.",
    "Neptune's winds are faster than the speed of sound on Earth.",
    "Neptune is about 4.5 billion kilometres from the Sun.",
    "Light takes over 4 hours to reach Neptune from the Sun.",
    "A year on Neptune lasts about 165 Earth years.",
    "Neptune has only completed one orbit since discovery.",
    "Neptune completed its first observed orbit in 2011.",
    "A day on Neptune lasts about 16 hours.",
    "Neptune is about four times wider than Earth.",
    "More than 57 Earths could fit inside Neptune.",
    "Neptune has a faint ring system.",
    "Neptune's rings are dark and patchy.",
    "The rings have bright arcs that are hard to explain.",
    "Neptune has at least 16 known moons.",
    "Triton is Neptune's largest moon.",
    "Triton orbits Neptune backward.",
    "Triton is the only large moon with a retrograde orbit.",
    "Triton was likely captured from the Kuiper Belt.",
    "Triton has geysers that erupt nitrogen gas.",
    "Triton's surface is bright and icy.",
    "Triton is one of the coldest worlds known.",
    "Triton is slowly spiraling toward Neptune.",
    "In billions of years Triton will be torn apart.",
    "Neptune's moon Nereid has a wildly eccentric orbit.",
    "Neptune's moon Proteus is oddly shaped.",
    "Voyager 2 is the only spacecraft to visit Neptune.",
    "Voyager 2 flew past Neptune in 1989.",
    "Voyager discovered Neptune's Great Dark Spot.",
    "The Great Dark Spot was a giant storm.",
    "The storm had winds up to 2,400 kilometres per hour.",
    "The original Great Dark Spot later vanished.",
    "New dark storms appear and fade on Neptune.",
    "Neptune has bright white methane clouds.",
    "The clouds race across the planet at huge speeds.",
    "Neptune radiates more heat than it receives.",
    "Neptune's internal heat drives its extreme weather.",
    "Neptune's atmosphere is mostly hydrogen and helium.",
    "Methane makes up a small but important fraction.",
    "Neptune has no solid surface.",
    "The planet's core is rocky and icy.",
    "Neptune's interior may hold diamond rain.",
    "Carbon in Neptune's depths could form diamond crystals.",
    "Diamonds may rain through Neptune's interior.",
    "Neptune has the most powerful storms of the ice giants.",
    "The planet's magnetic field is tilted and offset.",
    "Neptune's magnetic field is off-centre like Uranus'.",
    "Neptune's auroras are faint and rarely seen.",
    "Neptune's day is about 16 hours long.",
    "The planet was the last discovered by telescope search.",
    "Neptune is too faint to see without a telescope.",
    "A telescope or binoculars are needed to spot Neptune.",
    "Neptune's discovery kicked off a rivalry between nations.",
    "Both Britain and France claimed the discovery.",
    "John Couch Adams made similar predictions independently.",
    "Neptune's rings were discovered from Earth in 1984.",
    "Voyager confirmed the rings in 1989.",
    "Neptune's moon Triton was discovered days after the planet.",
    "William Lassell found Triton in 1846.",
    "Neptune has a blue-grey appearance in telescopes.",
    "Its colour varies with its bands of clouds.",
    "Neptune experiences violent dark spot storms.",
    "A dark spot observed in 2018 was surprisingly large.",
    "Neptune's weather changes rapidly over years.",
    "The planet's storms come and go quickly.",
    "Neptune's cloud tops are about -218°C.",
    "Triton's surface is even colder.",
    "Neptune's gravity is about 1.14 times Earth's.",
    "You would weigh slightly more on Neptune.",
    "Neptune has a huge supply of frozen gases.",
    "Its icy mantle is rich in water and methane.",
    "Neptune is the final planet in the classical system.",
    "Pluto's orbit crosses Neptune's at times.",
    "Neptune and Pluto are in a stable resonance.",
    "For every 2 Pluto orbits, Neptune makes 3.",
    "That resonance keeps them from colliding.",
    "Neptune's discovery expanded the solar system's boundaries.",
    "The planet was named soon after its discovery.",
    "Neptune's symbol is a trident.",
    "The trident symbol matches the god of the sea.",
    "Neptune has been visited by exactly one spacecraft.",
    "No mission is currently headed to Neptune.",
    "Scientists dream of a Neptune orbiter and Triton lander.",
    "NASA has studied concepts for a Neptune mission.",
    "Neptune's moon Triton may hide an ocean.",
    "Triton is a key target for future exploration.",
    "Neptune's faint rings are made of dust and ice.",
    "The rings may be replenished by meteor impacts.",
    "Neptune is the coldest planet in some measurements? No — Uranus is.",
    "Neptune is, however, windier than Uranus.",
    "Neptune's blue colour is more vivid than Uranus'.",
    "Neptune was once thought to be a quiet world.",
    "Voyager revealed it to be stormy and dynamic.",
    "Neptune remains a frontier for exploration."
  ]
};