/*
 * Squad Builder — player pool and formations.
 *
 * Valuations and ratings here are invented for the game. They are not
 * transfer fees, wages, or any real rating system, and nothing in this file
 * is sourced from a club or a data provider. Names are of well-known players
 * so the picking is fun; everything numeric next to them is made up.
 *
 *   i  id (stable — share links encode these)
 *   n  name        p  position: GK DEF MID FWD
 *   c  club        v  value in millions        r  rating 0-99
 */
window.SQUAD = {
  positions: ['GK', 'DEF', 'MID', 'FWD'],

  budgets: [
    { id:100, label:'£100m', note:'Tight. A legal XI fits, but only just — you will be shopping in the bargain bin.' },
    { id:200, label:'£200m', note:'Balanced. Two or three real names, the rest earned by scouting.' },
    { id:500, label:'£500m', note:'Silly money. Build the side you actually want.' },
  ],

  /* slot layout is in percent of the pitch: x across, y up from your own goal */
  formations: [
    { id:'442',  label:'4-4-2',   shape:[4,4,2] },
    { id:'433',  label:'4-3-3',   shape:[4,3,3] },
    { id:'352',  label:'3-5-2',   shape:[3,5,2] },
    { id:'532',  label:'5-3-2',   shape:[5,3,2] },
    { id:'4231', label:'4-2-3-1', shape:[4,2,3,1] },
    { id:'343',  label:'3-4-3',   shape:[3,4,3] },
  ],

  players: [
    /* ── goalkeepers */
    { i:1,  n:'Alisson',           p:'GK',  c:'Liverpool',      v:62, r:89 },
    { i:2,  n:'Ederson',           p:'GK',  c:'Man City',       v:58, r:88 },
    { i:3,  n:'Thibaut Courtois',  p:'GK',  c:'Real Madrid',    v:60, r:90 },
    { i:4,  n:'Marc-André ter Stegen', p:'GK', c:'Barcelona',   v:52, r:87 },
    { i:5,  n:'Gianluigi Donnarumma', p:'GK', c:'PSG',          v:56, r:87 },
    { i:6,  n:'Mike Maignan',      p:'GK',  c:'Milan',          v:48, r:86 },
    { i:7,  n:'David Raya',        p:'GK',  c:'Arsenal',        v:34, r:83 },
    { i:8,  n:'Jordan Pickford',   p:'GK',  c:'Everton',        v:24, r:81 },
    { i:9,  n:'Emiliano Martínez', p:'GK',  c:'Aston Villa',    v:30, r:84 },
    { i:10, n:'Guglielmo Vicario', p:'GK',  c:'Tottenham',      v:22, r:81 },
    { i:11, n:'Bart Verbruggen',   p:'GK',  c:'Brighton',       v:12, r:77 },
    { i:12, n:'Mads Hermansen',    p:'GK',  c:'Leicester',      v:7,  r:74 },
    { i:13, n:'Đorđe Petrović',    p:'GK',  c:'Strasbourg',     v:6,  r:73 },

    { i:14, n:'Caoimhín Kelleher',  p:'GK',  c:'Brentford',      v:9,  r:76 },
    { i:15, n:'Arijanet Muric',     p:'GK',  c:'Ipswich',        v:5,  r:72 },
    { i:16, n:'Alex Palmer',        p:'GK',  c:'Ipswich',        v:4,  r:71 },

    /* ── defenders */
    { i:20, n:'Rúben Dias',        p:'DEF', c:'Man City',       v:80, r:90 },
    { i:21, n:'Virgil van Dijk',   p:'DEF', c:'Liverpool',      v:62, r:89 },
    { i:22, n:'William Saliba',    p:'DEF', c:'Arsenal',        v:88, r:89 },
    { i:23, n:'Josko Gvardiol',    p:'DEF', c:'Man City',       v:84, r:87 },
    { i:24, n:'Antonio Rüdiger',   p:'DEF', c:'Real Madrid',    v:48, r:87 },
    { i:25, n:'Alessandro Bastoni',p:'DEF', c:'Inter',          v:76, r:87 },
    { i:26, n:'Éder Militão',      p:'DEF', c:'Real Madrid',    v:60, r:86 },
    { i:27, n:'Ronald Araújo',     p:'DEF', c:'Barcelona',      v:62, r:86 },
    { i:28, n:'Achraf Hakimi',     p:'DEF', c:'PSG',            v:72, r:87 },
    { i:29, n:'Theo Hernández',    p:'DEF', c:'Milan',          v:58, r:86 },
    { i:30, n:'Trent Alexander-Arnold', p:'DEF', c:'Real Madrid', v:78, r:88 },
    { i:31, n:'Alphonso Davies',   p:'DEF', c:'Bayern',         v:66, r:86 },
    { i:32, n:'Jeremie Frimpong',  p:'DEF', c:'Liverpool',      v:44, r:84 },
    { i:33, n:'Nuno Mendes',       p:'DEF', c:'PSG',            v:70, r:86 },
    { i:34, n:'Gabriel Magalhães', p:'DEF', c:'Arsenal',        v:64, r:87 },
    { i:35, n:'Cristian Romero',   p:'DEF', c:'Tottenham',      v:56, r:86 },
    { i:36, n:'Micky van de Ven',  p:'DEF', c:'Tottenham',      v:60, r:85 },
    { i:37, n:'Levi Colwill',      p:'DEF', c:'Chelsea',        v:46, r:83 },
    { i:38, n:'Marc Cucurella',    p:'DEF', c:'Chelsea',        v:34, r:83 },
    { i:39, n:'Pau Cubarsí',       p:'DEF', c:'Barcelona',      v:74, r:84 },
    { i:40, n:'Ezri Konsa',        p:'DEF', c:'Aston Villa',    v:32, r:81 },
    { i:41, n:'Dan Burn',          p:'DEF', c:'Newcastle',      v:12, r:78 },
    { i:42, n:'Pervis Estupiñán',  p:'DEF', c:'Milan',          v:26, r:81 },
    { i:43, n:'Milos Kerkez',      p:'DEF', c:'Liverpool',      v:40, r:82 },
    { i:44, n:'Jurriën Timber',    p:'DEF', c:'Arsenal',        v:52, r:84 },
    { i:45, n:'Nathan Aké',        p:'DEF', c:'Man City',       v:28, r:82 },
    { i:46, n:'Joachim Andersen',  p:'DEF', c:'Fulham',         v:20, r:80 },
    { i:47, n:'Murillo',           p:'DEF', c:'Nottm Forest',   v:38, r:82 },
    { i:48, n:'Ola Aina',          p:'DEF', c:'Nottm Forest',   v:14, r:78 },
    { i:49, n:'Rayan Aït-Nouri',   p:'DEF', c:'Man City',       v:36, r:81 },
    { i:50, n:'Maxence Lacroix',   p:'DEF', c:'Crystal Palace', v:16, r:79 },
    { i:51, n:'Jan Paul van Hecke',p:'DEF', c:'Brighton',       v:18, r:79 },
    { i:52, n:'Vitaliy Mykolenko', p:'DEF', c:'Everton',        v:9,  r:76 },
    { i:53, n:'Kristoffer Ajer',   p:'DEF', c:'Brentford',      v:8,  r:75 },
    { i:54, n:'Rico Lewis',        p:'DEF', c:'Man City',       v:30, r:80 },

    { i:55, n:'Nathan Patterson',   p:'DEF', c:'Everton',        v:6,  r:74 },
    { i:56, n:'Sepp van den Berg',  p:'DEF', c:'Brentford',      v:7,  r:75 },
    { i:57, n:'Ben Godfrey',        p:'DEF', c:'Atalanta',       v:4,  r:71 },
    { i:58, n:'Kenny Tete',         p:'DEF', c:'Fulham',         v:5,  r:73 },
    { i:59, n:'Rasmus Kristensen',  p:'DEF', c:'Eintracht',      v:8,  r:76 },

    /* ── midfielders */
    { i:60, n:'Rodri',             p:'MID', c:'Man City',       v:110,r:91 },
    { i:61, n:'Jude Bellingham',   p:'MID', c:'Real Madrid',    v:140,r:91 },
    { i:62, n:'Kevin De Bruyne',   p:'MID', c:'Napoli',         v:42, r:87 },
    { i:63, n:'Federico Valverde', p:'MID', c:'Real Madrid',    v:112,r:89 },
    { i:64, n:'Pedri',             p:'MID', c:'Barcelona',      v:118,r:89 },
    { i:65, n:'Gavi',              p:'MID', c:'Barcelona',      v:70, r:85 },
    { i:66, n:'Declan Rice',       p:'MID', c:'Arsenal',        v:96, r:88 },
    { i:67, n:'Martin Ødegaard',   p:'MID', c:'Arsenal',        v:88, r:88 },
    { i:68, n:'Bruno Fernandes',   p:'MID', c:'Man United',     v:62, r:87 },
    { i:69, n:'Cole Palmer',       p:'MID', c:'Chelsea',        v:120,r:88 },
    { i:70, n:'Enzo Fernández',    p:'MID', c:'Chelsea',        v:74, r:85 },
    { i:71, n:'Moisés Caicedo',    p:'MID', c:'Chelsea',        v:86, r:87 },
    { i:72, n:'Alexis Mac Allister',p:'MID',c:'Liverpool',      v:70, r:86 },
    { i:73, n:'Ryan Gravenberch',  p:'MID', c:'Liverpool',      v:68, r:85 },
    { i:74, n:'Dominik Szoboszlai',p:'MID', c:'Liverpool',      v:64, r:85 },
    { i:75, n:'Jamal Musiala',     p:'MID', c:'Bayern',         v:130,r:90 },
    { i:76, n:'Joshua Kimmich',    p:'MID', c:'Bayern',         v:58, r:87 },
    { i:77, n:'Nicolò Barella',    p:'MID', c:'Inter',          v:66, r:86 },
    { i:78, n:'Vitinha',           p:'MID', c:'PSG',            v:92, r:88 },
    { i:79, n:'João Neves',        p:'MID', c:'PSG',            v:98, r:87 },
    { i:80, n:'Warren Zaïre-Emery',p:'MID', c:'PSG',            v:72, r:84 },
    { i:81, n:'Bernardo Silva',    p:'MID', c:'Man City',       v:50, r:86 },
    { i:82, n:'Tijjani Reijnders', p:'MID', c:'Man City',       v:66, r:85 },
    { i:83, n:'Morgan Gibbs-White',p:'MID', c:'Nottm Forest',   v:44, r:83 },
    { i:84, n:'Bruno Guimarães',   p:'MID', c:'Newcastle',      v:60, r:86 },
    { i:85, n:'Sandro Tonali',     p:'MID', c:'Newcastle',      v:56, r:85 },
    { i:86, n:'Adam Wharton',      p:'MID', c:'Crystal Palace', v:48, r:82 },
    { i:87, n:'João Palhinha',     p:'MID', c:'Tottenham',      v:30, r:83 },
    { i:88, n:'Elliot Anderson',   p:'MID', c:'Nottm Forest',   v:40, r:82 },
    { i:89, n:'Carlos Baleba',     p:'MID', c:'Brighton',       v:52, r:82 },
    { i:90, n:'Alex Scott',        p:'MID', c:'Bournemouth',    v:18, r:78 },
    { i:91, n:'Idrissa Gueye',     p:'MID', c:'Everton',        v:6,  r:77 },
    { i:92, n:'Mateus Fernandes',  p:'MID', c:'Wolves',         v:14, r:78 },
    { i:93, n:'Kobbie Mainoo',     p:'MID', c:'Man United',     v:38, r:81 },
    { i:94, n:'Andreas Pereira',   p:'MID', c:'Palmeiras',      v:10, r:77 },

    { i:95, n:'Lewis Cook',         p:'MID', c:'Bournemouth',    v:7,  r:76 },
    { i:96, n:'Josh Brownhill',     p:'MID', c:'Burnley',        v:4,  r:71 },
    { i:97, n:'Flynn Downes',       p:'MID', c:'Southampton',    v:6,  r:74 },
    { i:98, n:'Hamed Traorè',       p:'MID', c:'Auxerre',        v:5,  r:73 },
    { i:99, n:'Jens Cajuste',       p:'MID', c:'Ipswich',        v:8,  r:75 },

    /* ── forwards */
    { i:100,n:'Erling Haaland',    p:'FWD', c:'Man City',       v:150,r:92 },
    { i:101,n:'Kylian Mbappé',     p:'FWD', c:'Real Madrid',    v:155,r:92 },
    { i:102,n:'Vinícius Júnior',   p:'FWD', c:'Real Madrid',    v:135,r:90 },
    { i:103,n:'Lamine Yamal',      p:'FWD', c:'Barcelona',      v:180,r:91 },
    { i:104,n:'Mohamed Salah',     p:'FWD', c:'Liverpool',      v:78, r:89 },
    { i:105,n:'Bukayo Saka',       p:'FWD', c:'Arsenal',        v:115,r:88 },
    { i:106,n:'Ousmane Dembélé',   p:'FWD', c:'PSG',            v:96, r:89 },
    { i:107,n:'Raphinha',          p:'FWD', c:'Barcelona',      v:102,r:89 },
    { i:108,n:'Harry Kane',        p:'FWD', c:'Bayern',         v:88, r:90 },
    { i:109,n:'Alexander Isak',    p:'FWD', c:'Liverpool',      v:118,r:88 },
    { i:110,n:'Viktor Gyökeres',   p:'FWD', c:'Arsenal',        v:76, r:85 },
    { i:111,n:'Robert Lewandowski',p:'FWD', c:'Barcelona',      v:32, r:86 },
    { i:112,n:'Lautaro Martínez',  p:'FWD', c:'Inter',          v:82, r:88 },
    { i:113,n:'Rafael Leão',       p:'FWD', c:'Milan',          v:74, r:85 },
    { i:114,n:'Michael Olise',     p:'FWD', c:'Bayern',         v:108,r:87 },
    { i:115,n:'Florian Wirtz',     p:'FWD', c:'Liverpool',      v:126,r:88 },
    { i:116,n:'Nico Williams',     p:'FWD', c:'Athletic Club',  v:86, r:85 },
    { i:117,n:'Julián Álvarez',    p:'FWD', c:'Atlético',       v:94, r:87 },
    { i:118,n:'Bradley Barcola',   p:'FWD', c:'PSG',            v:70, r:84 },
    { i:119,n:'Désiré Doué',       p:'FWD', c:'PSG',            v:92, r:85 },
    { i:120,n:'Hugo Ekitiké',      p:'FWD', c:'Liverpool',      v:68, r:83 },
    { i:121,n:'Matheus Cunha',     p:'FWD', c:'Man United',     v:54, r:83 },
    { i:122,n:'Bryan Mbeumo',      p:'FWD', c:'Man United',     v:56, r:83 },
    { i:123,n:'Ollie Watkins',     p:'FWD', c:'Aston Villa',    v:46, r:84 },
    { i:124,n:'Jean-Philippe Mateta',p:'FWD',c:'Crystal Palace',v:34, r:82 },
    { i:125,n:'Yoane Wissa',       p:'FWD', c:'Newcastle',      v:26, r:81 },
    { i:126,n:'Chris Wood',        p:'FWD', c:'Nottm Forest',   v:16, r:80 },
    { i:127,n:'Jarrod Bowen',      p:'FWD', c:'West Ham',       v:30, r:82 },
    { i:128,n:'Antoine Semenyo',   p:'FWD', c:'Bournemouth',    v:44, r:82 },
    { i:129,n:'Jørgen Strand Larsen',p:'FWD',c:'Wolves',        v:22, r:80 },
    { i:130,n:'Beto',              p:'FWD', c:'Everton',        v:8,  r:75 },
    { i:131,n:'Danny Welbeck',     p:'FWD', c:'Brighton',       v:10, r:78 },
    { i:132,n:'Kevin Schade',      p:'FWD', c:'Brentford',      v:20, r:79 },
    { i:133,n:'Rodrigo Muniz',     p:'FWD', c:'Fulham',         v:14, r:78 },
    { i:134,n:'Armando Broja',      p:'FWD', c:'Burnley',        v:7,  r:75 },
    { i:135,n:'Josh King',          p:'FWD', c:'Bournemouth',    v:5,  r:72 },
    { i:136,n:'Cameron Archer',     p:'FWD', c:'Southampton',    v:6,  r:74 },
    { i:137,n:'Divin Mubama',       p:'FWD', c:'Man City',       v:9,  r:76 },
  ],
};
